repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: requirements-txt-fixer
-   repo: https://github.com/PyCQA/pylint
    rev:  pylint-3.0.0a3
    hooks:
    -   id: pylint
        exclude: ^(tests)/
-   repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
    -   id: black
