name: Lint Package

on:
  push:
    branches:
      - '*.x'
      - 'develop'
  pull_request:
    branches:
      - '*.x'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements/default.txt
    - name: Lint with Pylint
      run: |
        pylint vaccination
